config/routes.rb
Rails.application.routes.draw do 

  root 'static_pages#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'password_resets/new'
  get 'password_resets/edit'

  resources :users do
    member do 
      get :following, :followers      
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
    - object.errors.full_messages.each do |msg|
      %li= msg

app/views/shared/_feed.html.haml
- if @feed_items.any?
  %ol.microposts
    = render @feed_items
  = will_paginate @feed_items

app/views/shared/_logged_in_home.html.haml
.row
  %aside.col-md-4
    %section.user_info
      = render 'shared/user_info'
    %section.stats
      = render 'shared/stats'
    %section.micropost_form
      = render 'shared/micropost_form'
  .col-md-8
    %h3 Micropost Feed
    = render 'shared/feed'

app/views/shared/_logged_out_home.html.haml
.center.jumbotron
  %h1 Welcome to the MicroBlogger

  = link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"

app/views/shared/_micropost_form.html.haml
= form_for(@micropost, html: { multipart: true }) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.text_area :content, placeholder: "Compose new micropost..."
  = f.submit "Post", class: "btn btn-primary"
  %span.picture
    = f.file_field :picture, accept: "image/jpeg, image/gif, image/png"

app/views/shared/_stats.html.haml
- @user ||= current_user
.stats
  %a{:href => "#{following_user_path(@user)}"}
    %strong#following.stat
      = @user.following.count
    following
  %a{:href => "#{followers_user_path(@user)}"}
    %strong#followers.stat
      = followers_count = @user.followers.count
    %strong#followers_count.stat
      = "follower".pluralize(followers_count)

app/views/shared/_user_info.html.haml
= link_to gravatar_for(current_user, size: 50), current_user
%h1= current_user.name
%span= link_to "view my profile", current_user
%span= pluralize(current_user.microposts.count, "micropost")